/**
 * Dashboard-side mirror of the backend collection config.
 * Drives the CRUD pages and dynamic forms.
 */
export const COLLECTIONS = {
  slides: {
    key: 'slides',
    label: { en: 'Slideshow Images', ar: 'صور العرض' },
    icon: 'images',
    single: false,
    fields: [
      { name: 'title', type: 'string', locale: 'en', label: 'Title', required: true },
      { name: 'title', type: 'string', locale: 'ar', label: 'العنوان', required: true },
      { name: 'subtitle', type: 'string', locale: 'en', label: 'Subtitle' },
      { name: 'subtitle', type: 'string', locale: 'ar', label: 'الوصف الفرعي' },
      { name: 'image', type: 'image', label: 'Image', required: true },
      { name: 'link', type: 'url', label: 'Link' },
      { name: 'active', type: 'boolean', label: 'Active' },
      { name: 'sort_order', type: 'number', label: 'Sort Order' },
    ],
  },
  projects: {
    key: 'projects',
    label: { en: 'Projects', ar: 'المشاريع' },
    icon: 'briefcase',
    single: false,
    fields: [
      { name: 'title', type: 'string', locale: 'en', label: 'Title', required: true },
      { name: 'title', type: 'string', locale: 'ar', label: 'العنوان', required: true },
      { name: 'summary', type: 'textarea', locale: 'en', label: 'Summary' },
      { name: 'summary', type: 'textarea', locale: 'ar', label: 'الملخص' },
      { name: 'description', type: 'textarea', locale: 'en', label: 'Full Description' },
      { name: 'description', type: 'textarea', locale: 'ar', label: 'الوصف الكامل' },
      { name: 'category', type: 'string', label: 'Category' },
      { name: 'tech_stack', type: 'tags', label: 'Tech Stack' },
      { name: 'image', type: 'image', label: 'Cover Image' },
      { name: 'gallery', type: 'images', label: 'Gallery Images' },
      { name: 'github_url', type: 'url', label: 'GitHub URL' },
      { name: 'live_url', type: 'url', label: 'Live URL' },
      { name: 'start_date', type: 'date', label: 'Start Date' },
      { name: 'end_date', type: 'date', label: 'End Date' },
      { name: 'featured', type: 'boolean', label: 'Featured' },
      { name: 'published', type: 'boolean', label: 'Published' },
      { name: 'sort_order', type: 'number', label: 'Sort Order' },
    ],
  },
  experiences: {
    key: 'experiences',
    label: { en: 'Experiences', ar: 'الخبرات' },
    icon: 'building',
    single: false,
    fields: [
      { name: 'role', type: 'string', locale: 'en', label: 'Role', required: true },
      { name: 'role', type: 'string', locale: 'ar', label: 'المسمى الوظيفي', required: true },
      { name: 'company', type: 'string', label: 'Company', required: true },
      { name: 'company_logo', type: 'image', label: 'Company Logo' },
      { name: 'location', type: 'string', locale: 'en', label: 'Location' },
      { name: 'location', type: 'string', locale: 'ar', label: 'الموقع' },
      { name: 'description', type: 'textarea', locale: 'en', label: 'Description' },
      { name: 'description', type: 'textarea', locale: 'ar', label: 'الوصف' },
      { name: 'start_date', type: 'date', label: 'Start Date' },
      { name: 'end_date', type: 'date', label: 'End Date' },
      { name: 'current', type: 'boolean', label: 'Current Position' },
      { name: 'sort_order', type: 'number', label: 'Sort Order' },
    ],
  },
  trophies: {
    key: 'trophies',
    label: { en: 'Trophies / Awards', ar: 'الجوائز' },
    icon: 'trophy',
    single: false,
    fields: [
      { name: 'title', type: 'string', locale: 'en', label: 'Title', required: true },
      { name: 'title', type: 'string', locale: 'ar', label: 'العنوان', required: true },
      { name: 'description', type: 'textarea', locale: 'en', label: 'Description' },
      { name: 'description', type: 'textarea', locale: 'ar', label: 'الوصف' },
      { name: 'issuer', type: 'string', label: 'Issuer' },
      { name: 'year', type: 'number', label: 'Year' },
      { name: 'image', type: 'image', label: 'Image' },
      { name: 'sort_order', type: 'number', label: 'Sort Order' },
    ],
  },
  certificates: {
    key: 'certificates',
    label: { en: 'Certificates', ar: 'الشهادات' },
    icon: 'award',
    single: false,
    fields: [
      { name: 'title', type: 'string', locale: 'en', label: 'Title', required: true },
      { name: 'title', type: 'string', locale: 'ar', label: 'العنوان', required: true },
      { name: 'issuer', type: 'string', label: 'Issuer', required: true },
      { name: 'description', type: 'textarea', locale: 'en', label: 'Description' },
      { name: 'description', type: 'textarea', locale: 'ar', label: 'الوصف' },
      { name: 'image', type: 'image', label: 'Image' },
      { name: 'credential_url', type: 'url', label: 'Credential URL' },
      { name: 'issue_date', type: 'date', label: 'Issue Date' },
      { name: 'expiry_date', type: 'date', label: 'Expiry Date' },
      { name: 'sort_order', type: 'number', label: 'Sort Order' },
    ],
  },
  participations: {
    key: 'participations',
    label: { en: 'Participations', ar: 'المشاركات' },
    icon: 'users',
    single: false,
    fields: [
      { name: 'title', type: 'string', locale: 'en', label: 'Title', required: true },
      { name: 'title', type: 'string', locale: 'ar', label: 'العنوان', required: true },
      { name: 'event_type', type: 'string', label: 'Event Type' },
      { name: 'role', type: 'string', locale: 'en', label: 'Role' },
      { name: 'role', type: 'string', locale: 'ar', label: 'الدور' },
      { name: 'description', type: 'textarea', locale: 'en', label: 'Description' },
      { name: 'description', type: 'textarea', locale: 'ar', label: 'الوصف' },
      { name: 'location', type: 'string', locale: 'en', label: 'Location' },
      { name: 'location', type: 'string', locale: 'ar', label: 'الموقع' },
      { name: 'date', type: 'date', label: 'Date' },
      { name: 'image', type: 'image', label: 'Image' },
      { name: 'link', type: 'url', label: 'Link' },
      { name: 'sort_order', type: 'number', label: 'Sort Order' },
    ],
  },
  skills: {
    key: 'skills',
    label: { en: 'Skills', ar: 'المهارات' },
    icon: 'code',
    single: false,
    fields: [
      { name: 'name', type: 'string', locale: 'en', label: 'Name', required: true },
      { name: 'name', type: 'string', locale: 'ar', label: 'الاسم', required: true },
      {
        name: 'category', type: 'select', label: 'Category',
        options: ['Languages', 'Frameworks', 'Tools', 'Databases', 'Soft Skills', 'Other'],
      },
      { name: 'icon', type: 'string', label: 'Icon (FA class)' },
      { name: 'level', type: 'number', label: 'Proficiency 0-100' },
      { name: 'sort_order', type: 'number', label: 'Sort Order' },
    ],
  },
  educations: {
    key: 'educations',
    label: { en: 'Education', ar: 'التعليم' },
    icon: 'graduation',
    single: false,
    fields: [
      { name: 'degree', type: 'string', locale: 'en', label: 'Degree', required: true },
      { name: 'degree', type: 'string', locale: 'ar', label: 'الشهادة', required: true },
      { name: 'institution', type: 'string', label: 'Institution', required: true },
      { name: 'field', type: 'string', locale: 'en', label: 'Field of Study' },
      { name: 'field', type: 'string', locale: 'ar', label: 'التخصص' },
      { name: 'description', type: 'textarea', locale: 'en', label: 'Description' },
      { name: 'description', type: 'textarea', locale: 'ar', label: 'الوصف' },
      { name: 'start_date', type: 'date', label: 'Start Date' },
      { name: 'end_date', type: 'date', label: 'End Date' },
      { name: 'sort_order', type: 'number', label: 'Sort Order' },
    ],
  },
  services: {
    key: 'services',
    label: { en: 'Services', ar: 'الخدمات' },
    icon: 'wrench',
    single: false,
    fields: [
      { name: 'title', type: 'string', locale: 'en', label: 'Title', required: true },
      { name: 'title', type: 'string', locale: 'ar', label: 'العنوان', required: true },
      { name: 'description', type: 'textarea', locale: 'en', label: 'Description' },
      { name: 'description', type: 'textarea', locale: 'ar', label: 'الوصف' },
      { name: 'icon', type: 'string', label: 'Icon (FA class)' },
      { name: 'sort_order', type: 'number', label: 'Sort Order' },
    ],
  },
  testimonials: {
    key: 'testimonials',
    label: { en: 'Testimonials', ar: 'آراء العملاء' },
    icon: 'quote',
    single: false,
    fields: [
      { name: 'name', type: 'string', label: 'Name', required: true },
      { name: 'role', type: 'string', locale: 'en', label: 'Role' },
      { name: 'role', type: 'string', locale: 'ar', label: 'الدور' },
      { name: 'company', type: 'string', label: 'Company' },
      { name: 'content', type: 'textarea', locale: 'en', label: 'Testimonial', required: true },
      { name: 'content', type: 'textarea', locale: 'ar', label: 'شهادة', required: true },
      { name: 'avatar', type: 'image', label: 'Avatar' },
      { name: 'sort_order', type: 'number', label: 'Sort Order' },
    ],
  },
  posts: {
    key: 'posts',
    label: { en: 'Blog Posts', ar: 'مقالات المدونة' },
    icon: 'file',
    single: false,
    fields: [
      { name: 'title', type: 'string', locale: 'en', label: 'Title', required: true },
      { name: 'title', type: 'string', locale: 'ar', label: 'العنوان', required: true },
      { name: 'excerpt', type: 'textarea', locale: 'en', label: 'Excerpt' },
      { name: 'excerpt', type: 'textarea', locale: 'ar', label: 'المقتطف' },
      { name: 'content', type: 'textarea', locale: 'en', label: 'Content (markdown)' },
      { name: 'content', type: 'textarea', locale: 'ar', label: 'المحتوى' },
      { name: 'category', type: 'string', label: 'Category' },
      { name: 'image', type: 'image', label: 'Cover Image' },
      { name: 'published', type: 'boolean', label: 'Published' },
      { name: 'sort_order', type: 'number', label: 'Sort Order' },
    ],
  },
  socials: {
    key: 'socials',
    label: { en: 'Social Links', ar: 'روابط التواصل' },
    icon: 'share',
    single: false,
    fields: [
      { name: 'label', type: 'string', label: 'Label', required: true },
      { name: 'url', type: 'url', label: 'URL', required: true },
      { name: 'icon', type: 'string', label: 'Icon (FA class)' },
      { name: 'sort_order', type: 'number', label: 'Sort Order' },
    ],
  },
};
