/**
 * Master configuration for every editable collection.
 * Drives: table auto-creation, generic CRUD API, dashboard forms, and seeding.
 *
 * field types: string, text, textarea, number, date, boolean, image, images, select, tags, email, url
 * locale: 'en' | 'ar' | null  (en/ar fields are stored as <name>_en / <name>_ar)
 */
const collections = {
  slides: {
    table: 'slides',
    label: 'Slideshow Images',
    singular: 'slide',
    icon: 'images',
    public: true,
    publicKey: 'slides',
    sortBy: 'sort_order',
    sortDir: 'ASC',
    fields: [
      { name: 'title', type: 'string', locale: 'en', label: 'Title' },
      { name: 'title', type: 'string', locale: 'ar', label: 'العنوان' },
      { name: 'subtitle', type: 'string', locale: 'en', label: 'Subtitle' },
      { name: 'subtitle', type: 'string', locale: 'ar', label: 'الوصف الفرعي' },
      { name: 'image', type: 'image', label: 'Image' },
      { name: 'link', type: 'url', label: 'Link', optional: true },
      { name: 'active', type: 'boolean', label: 'Active', default: true },
      { name: 'sort_order', type: 'number', label: 'Sort Order', default: 0 },
    ],
  },

  projects: {
    table: 'projects',
    label: 'Projects',
    singular: 'project',
    icon: 'briefcase',
    public: true,
    publicKey: 'projects',
    sortBy: 'sort_order',
    sortDir: 'DESC',
    fields: [
      { name: 'title', type: 'string', locale: 'en', label: 'Title' },
      { name: 'title', type: 'string', locale: 'ar', label: 'العنوان' },
      { name: 'summary', type: 'textarea', locale: 'en', label: 'Summary' },
      { name: 'summary', type: 'textarea', locale: 'ar', label: 'الملخص' },
      { name: 'description', type: 'textarea', locale: 'en', label: 'Full Description', optional: true },
      { name: 'description', type: 'textarea', locale: 'ar', label: 'الوصف الكامل', optional: true },
      { name: 'category', type: 'string', label: 'Category', optional: true },
      { name: 'tech_stack', type: 'tags', label: 'Tech Stack (comma separated)' },
      { name: 'image', type: 'image', label: 'Cover Image', optional: true },
      { name: 'gallery', type: 'images', label: 'Gallery Images', optional: true },
      { name: 'github_url', type: 'url', label: 'GitHub URL', optional: true },
      { name: 'live_url', type: 'url', label: 'Live URL', optional: true },
      { name: 'start_date', type: 'date', label: 'Start Date', optional: true },
      { name: 'end_date', type: 'date', label: 'End Date', optional: true },
      { name: 'featured', type: 'boolean', label: 'Featured', default: false },
      { name: 'published', type: 'boolean', label: 'Published', default: true },
      { name: 'sort_order', type: 'number', label: 'Sort Order', default: 0 },
    ],
  },

  experiences: {
    table: 'experiences',
    label: 'Experiences',
    singular: 'experience',
    icon: 'building',
    public: true,
    publicKey: 'experiences',
    sortBy: 'start_date',
    sortDir: 'DESC',
    fields: [
      { name: 'role', type: 'string', locale: 'en', label: 'Role' },
      { name: 'role', type: 'string', locale: 'ar', label: 'المسمى الوظيفي' },
      { name: 'company', type: 'string', label: 'Company' },
      { name: 'company_logo', type: 'image', label: 'Company Logo', optional: true },
      { name: 'location', type: 'string', locale: 'en', label: 'Location', optional: true },
      { name: 'location', type: 'string', locale: 'ar', label: 'الموقع', optional: true },
      { name: 'description', type: 'textarea', locale: 'en', label: 'Description' },
      { name: 'description', type: 'textarea', locale: 'ar', label: 'الوصف' },
      { name: 'start_date', type: 'date', label: 'Start Date' },
      { name: 'end_date', type: 'date', label: 'End Date', optional: true },
      { name: 'current', type: 'boolean', label: 'Current Position', default: false },
      { name: 'sort_order', type: 'number', label: 'Sort Order', default: 0 },
    ],
  },

  trophies: {
    table: 'trophies',
    label: 'Trophies / Awards',
    singular: 'trophy',
    icon: 'trophy',
    public: true,
    publicKey: 'trophies',
    sortBy: 'year',
    sortDir: 'DESC',
    fields: [
      { name: 'title', type: 'string', locale: 'en', label: 'Title' },
      { name: 'title', type: 'string', locale: 'ar', label: 'العنوان' },
      { name: 'description', type: 'textarea', locale: 'en', label: 'Description', optional: true },
      { name: 'description', type: 'textarea', locale: 'ar', label: 'الوصف', optional: true },
      { name: 'issuer', type: 'string', label: 'Issuer / Organization', optional: true },
      { name: 'year', type: 'number', label: 'Year', optional: true },
      { name: 'image', type: 'image', label: 'Image', optional: true },
      { name: 'sort_order', type: 'number', label: 'Sort Order', default: 0 },
    ],
  },

  certificates: {
    table: 'certificates',
    label: 'Certificates',
    singular: 'certificate',
    icon: 'award',
    public: true,
    publicKey: 'certificates',
    sortBy: 'issue_date',
    sortDir: 'DESC',
    fields: [
      { name: 'title', type: 'string', locale: 'en', label: 'Title' },
      { name: 'title', type: 'string', locale: 'ar', label: 'العنوان' },
      { name: 'issuer', type: 'string', label: 'Issuer' },
      { name: 'description', type: 'textarea', locale: 'en', label: 'Description', optional: true },
      { name: 'description', type: 'textarea', locale: 'ar', label: 'الوصف', optional: true },
      { name: 'image', type: 'image', label: 'Image', optional: true },
      { name: 'credential_url', type: 'url', label: 'Credential URL', optional: true },
      { name: 'issue_date', type: 'date', label: 'Issue Date', optional: true },
      { name: 'expiry_date', type: 'date', label: 'Expiry Date', optional: true },
      { name: 'sort_order', type: 'number', label: 'Sort Order', default: 0 },
    ],
  },

  participations: {
    table: 'participations',
    label: 'Participations / Events',
    singular: 'participation',
    icon: 'users',
    public: true,
    publicKey: 'participations',
    sortBy: 'date',
    sortDir: 'DESC',
    fields: [
      { name: 'title', type: 'string', locale: 'en', label: 'Title' },
      { name: 'title', type: 'string', locale: 'ar', label: 'العنوان' },
      { name: 'event_type', type: 'string', label: 'Event Type (Hackathon, Conference, ...)', optional: true },
      { name: 'role', type: 'string', locale: 'en', label: 'Role', optional: true },
      { name: 'role', type: 'string', locale: 'ar', label: 'الدور', optional: true },
      { name: 'description', type: 'textarea', locale: 'en', label: 'Description', optional: true },
      { name: 'description', type: 'textarea', locale: 'ar', label: 'الوصف', optional: true },
      { name: 'location', type: 'string', locale: 'en', label: 'Location', optional: true },
      { name: 'location', type: 'string', locale: 'ar', label: 'الموقع', optional: true },
      { name: 'date', type: 'date', label: 'Date', optional: true },
      { name: 'image', type: 'image', label: 'Image', optional: true },
      { name: 'link', type: 'url', label: 'Link', optional: true },
      { name: 'sort_order', type: 'number', label: 'Sort Order', default: 0 },
    ],
  },

  skills: {
    table: 'skills',
    label: 'Skills',
    singular: 'skill',
    icon: 'code',
    public: true,
    publicKey: 'skills',
    sortBy: 'sort_order',
    sortDir: 'ASC',
    fields: [
      { name: 'name', type: 'string', locale: 'en', label: 'Name' },
      { name: 'name', type: 'string', locale: 'ar', label: 'الاسم' },
      { name: 'category', type: 'select', label: 'Category', options: ['Languages', 'Frameworks', 'Tools', 'Databases', 'Soft Skills', 'Other'] },
      { name: 'icon', type: 'string', label: 'Icon (Font Awesome class or emoji)', optional: true },
      { name: 'level', type: 'number', label: 'Proficiency 0-100', default: 80 },
      { name: 'sort_order', type: 'number', label: 'Sort Order', default: 0 },
    ],
  },

  educations: {
    table: 'educations',
    label: 'Education',
    singular: 'education',
    icon: 'graduation',
    public: true,
    publicKey: 'educations',
    sortBy: 'start_date',
    sortDir: 'DESC',
    fields: [
      { name: 'degree', type: 'string', locale: 'en', label: 'Degree' },
      { name: 'degree', type: 'string', locale: 'ar', label: 'الشهادة' },
      { name: 'institution', type: 'string', label: 'Institution' },
      { name: 'field', type: 'string', locale: 'en', label: 'Field of Study', optional: true },
      { name: 'field', type: 'string', locale: 'ar', label: 'التخصص', optional: true },
      { name: 'description', type: 'textarea', locale: 'en', label: 'Description', optional: true },
      { name: 'description', type: 'textarea', locale: 'ar', label: 'الوصف', optional: true },
      { name: 'start_date', type: 'date', label: 'Start Date', optional: true },
      { name: 'end_date', type: 'date', label: 'End Date', optional: true },
      { name: 'sort_order', type: 'number', label: 'Sort Order', default: 0 },
    ],
  },

  services: {
    table: 'services',
    label: 'Services',
    singular: 'service',
    icon: 'wrench',
    public: true,
    publicKey: 'services',
    sortBy: 'sort_order',
    sortDir: 'ASC',
    fields: [
      { name: 'title', type: 'string', locale: 'en', label: 'Title' },
      { name: 'title', type: 'string', locale: 'ar', label: 'العنوان' },
      { name: 'description', type: 'textarea', locale: 'en', label: 'Description' },
      { name: 'description', type: 'textarea', locale: 'ar', label: 'الوصف' },
      { name: 'icon', type: 'string', label: 'Icon (Font Awesome class or emoji)', optional: true },
      { name: 'sort_order', type: 'number', label: 'Sort Order', default: 0 },
    ],
  },

  testimonials: {
    table: 'testimonials',
    label: 'Testimonials',
    singular: 'testimonial',
    icon: 'quote',
    public: true,
    publicKey: 'testimonials',
    sortBy: 'sort_order',
    sortDir: 'ASC',
    fields: [
      { name: 'name', type: 'string', label: 'Name' },
      { name: 'role', type: 'string', locale: 'en', label: 'Role / Title' },
      { name: 'role', type: 'string', locale: 'ar', label: 'الدور' },
      { name: 'company', type: 'string', label: 'Company', optional: true },
      { name: 'content', type: 'textarea', locale: 'en', label: 'Testimonial' },
      { name: 'content', type: 'textarea', locale: 'ar', label: 'شهادة' },
      { name: 'avatar', type: 'image', label: 'Avatar', optional: true },
      { name: 'sort_order', type: 'number', label: 'Sort Order', default: 0 },
    ],
  },

  posts: {
    table: 'posts',
    label: 'Blog Posts',
    singular: 'post',
    icon: 'file',
    public: true,
    publicKey: 'posts',
    sortBy: 'created_at',
    sortDir: 'DESC',
    fields: [
      { name: 'title', type: 'string', locale: 'en', label: 'Title' },
      { name: 'title', type: 'string', locale: 'ar', label: 'العنوان' },
      { name: 'excerpt', type: 'textarea', locale: 'en', label: 'Excerpt', optional: true },
      { name: 'excerpt', type: 'textarea', locale: 'ar', label: 'المقتطف', optional: true },
      { name: 'content', type: 'textarea', locale: 'en', label: 'Content (markdown supported)' },
      { name: 'content', type: 'textarea', locale: 'ar', label: 'المحتوى' },
      { name: 'category', type: 'string', label: 'Category', optional: true },
      { name: 'image', type: 'image', label: 'Cover Image', optional: true },
      { name: 'published', type: 'boolean', label: 'Published', default: true },
      { name: 'sort_order', type: 'number', label: 'Sort Order', default: 0 },
    ],
  },

  socials: {
    table: 'social_links',
    label: 'Social Links',
    singular: 'social',
    icon: 'share',
    public: true,
    publicKey: 'socials',
    sortBy: 'sort_order',
    sortDir: 'ASC',
    fields: [
      { name: 'label', type: 'string', label: 'Label (e.g. GitHub)' },
      { name: 'url', type: 'url', label: 'URL' },
      { name: 'icon', type: 'string', label: 'Icon (Font Awesome class)', optional: true },
      { name: 'sort_order', type: 'number', label: 'Sort Order', default: 0 },
    ],
  },

  messages: {
    table: 'contact_messages',
    label: 'Contact Messages',
    singular: 'message',
    icon: 'envelope',
    public: false,
    sortBy: 'created_at',
    sortDir: 'DESC',
    readOnly: true,
    fields: [
      { name: 'name', type: 'string', label: 'Name' },
      { name: 'email', type: 'email', label: 'Email' },
      { name: 'subject', type: 'string', label: 'Subject' },
      { name: 'message', type: 'textarea', label: 'Message' },
      { name: 'is_read', type: 'boolean', label: 'Read' },
    ],
  },
};

module.exports = { collections };
